import React from 'react';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { expect, it, vi } from 'vitest';
import { buildPaymentModel } from '../../src/features/organizer/payments/paymentModel';
import { PaymentsPanel } from '../../src/features/organizer/payments/PaymentsPanel';
const model = buildPaymentModel({ leftAxis: [], topAxis: [], squares: [['Buyer'], ['Other']], allocationLabels: ['Family', 'Family'] }, {});
const props = { open: true, onClose: vi.fn(), model, onViewSquare: vi.fn(), onSave: vi.fn(async () => {}) };
it('searches permanent numbers and never updates hidden selections', async () => {
  render(<PaymentsPanel {...props} />);
  fireEvent.click(screen.getByRole('button', { name: /Show squares for Family/ }));
  fireEvent.click(screen.getByLabelText('Select square 1'));
  fireEvent.change(screen.getByLabelText('Search people, names or square number'), { target: { value: '2' } });
  expect(screen.queryByRole('button', { name: 'Mark 0 selected paid' })).not.toBeInTheDocument();
  fireEvent.click(screen.getByLabelText('Select square 2'));
  fireEvent.click(screen.getByRole('button', { name: 'Mark 1 selected paid' }));
  await waitFor(() => expect(props.onSave).toHaveBeenCalledWith([1], 'paid'));
});
it('awaits persistence and preserves selection and requested status for retry', async () => {
  let reject!: (reason: Error) => void;
  const onSave = vi.fn().mockImplementationOnce(() => new Promise((_, fail) => { reject = fail; })).mockResolvedValue(undefined);
  render(<PaymentsPanel {...props} onSave={onSave} />);
  fireEvent.click(screen.getByRole('button', { name: /Show squares for Family/ }));
  fireEvent.click(screen.getByLabelText('Select square 1'));
  fireEvent.click(screen.getByRole('button', { name: 'Mark 1 selected unpaid' }));
  expect(screen.getByRole('status')).toHaveTextContent('Saving');
  reject(new Error('Offline'));
  await screen.findByRole('alert');
  expect(screen.getByLabelText('Select square 1')).toBeChecked();
  fireEvent.click(screen.getByRole('button', { name: 'Retry marking 1 selected unpaid' }));
  await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('Saved'));
  expect(onSave).toHaveBeenLastCalledWith([0], 'unpaid');
  expect(screen.getByLabelText('Select square 1')).not.toBeChecked();
});
it('supports initial filtering, private copy, view on board and empty results', () => {
  const onViewSquare = vi.fn();
  render(<PaymentsPanel {...props} initialQuery="Buyer" initialFilter="unknown" onViewSquare={onViewSquare} />);
  expect(screen.getByText(/Private to you/)).toBeInTheDocument();
  fireEvent.click(screen.getByRole('button', { name: /Show squares for Family/ }));
  fireEvent.click(screen.getByRole('button', { name: 'View square 1 on board' }));
  expect(onViewSquare).toHaveBeenCalledWith(0);
  fireEvent.change(screen.getByLabelText('Search people, names or square number'), { target: { value: 'Missing' } });
  expect(screen.getByText('No matching squares.')).toBeInTheDocument();
});
it('clears selections when collapsing a group and closes with Escape', () => {
  const onClose = vi.fn();
  render(<PaymentsPanel {...props} onClose={onClose} />);
  expect(screen.getByLabelText('Search people, names or square number')).toHaveFocus();
  fireEvent.click(screen.getByRole('button', { name: /Show squares for Family/ }));
  fireEvent.click(screen.getByLabelText('Select square 1'));
  fireEvent.click(screen.getByRole('button', { name: /Hide squares for Family/ }));
  expect(screen.queryByRole('button', { name: 'Mark 0 selected paid' })).not.toBeInTheDocument();
  fireEvent.keyDown(screen.getByRole('dialog'), { key: 'Escape' });
  expect(onClose).toHaveBeenCalledOnce();
});
it('never treats a status filter or search as bulk selection', () => {
  render(<PaymentsPanel {...props} initialFilter="unknown" />);
  fireEvent.click(screen.getByRole('button', { name: /Show squares for Family/ }));
  expect(screen.queryByRole('button', { name: 'Mark 0 selected paid' })).not.toBeInTheDocument();
  fireEvent.click(screen.getByLabelText('Select square 1'));
  fireEvent.click(screen.getByRole('button', { name: 'Paid · 0 squares' }));
  expect(screen.queryByRole('button', { name: 'Mark 0 selected paid' })).not.toBeInTheDocument();
});
it('selects only shown squares for a family and supports clearing the group', () => {
  render(<PaymentsPanel {...props} initialQuery="Buyer" />);
  fireEvent.click(screen.getByRole('button', { name: 'Show squares for Family' }));
  fireEvent.click(screen.getByRole('button', { name: 'Select 1 shown squares for Family' }));
  expect(screen.getByLabelText('Select square 1')).toBeChecked();
  expect(screen.queryByLabelText('Select square 2')).not.toBeInTheDocument();
  expect(screen.getByRole('button', { name: 'Mark 1 selected paid' })).toBeEnabled();
  fireEvent.click(screen.getByRole('button', { name: 'Clear 1 shown squares for Family' }));
  expect(screen.getByText('Mark a person’s squares paid in one step. Show squares to make individual changes.')).toBeInTheDocument();
});
it('requires a new selection when refresh changes the failed save scope', async () => {
  const onSave = vi.fn().mockRejectedValue(new Error('Offline'));
  const { rerender } = render(<PaymentsPanel {...props} initialFilter="unknown" onSave={onSave} />);
  fireEvent.click(screen.getByRole('button', { name: 'Show squares for Family' }));
  fireEvent.click(screen.getByRole('button', { name: 'Select 2 shown squares for Family' }));
  fireEvent.click(screen.getByRole('button', { name: 'Mark 2 selected paid' }));
  await screen.findByRole('alert');
  const refreshed = { ...model, groups: model.groups.map(group => ({ ...group, squares: group.squares.map(square => square.index === 0 ? { ...square, status: 'paid' as const } : square) })) };
  rerender(<PaymentsPanel {...props} model={refreshed} initialFilter="unknown" onSave={onSave} />);
  expect(screen.queryByRole('button', { name: /Retry marking/ })).not.toBeInTheDocument();
  expect(screen.getByText(/The shown squares changed/)).toBeInTheDocument();
  expect(onSave).toHaveBeenCalledTimes(1);
});
it('marks the whole responsible group paid from its collapsed row, including filtered-out squares', async () => {
  const onSave = vi.fn().mockResolvedValue(undefined);
  const grouped = buildPaymentModel({ leftAxis: [], topAxis: [], squares: [['One'], ['Two'], ['Three'], ['Else']], allocationLabels: ['Family', 'Family', 'Family', 'Other'] }, { 0: { cell_index: 0, paid_status: 'paid', notify_opt_in: false, contact_type: null, contact_value: null }, 1: { cell_index: 1, paid_status: 'unpaid', notify_opt_in: false, contact_type: null, contact_value: null } });
  render(<PaymentsPanel {...props} model={grouped} initialQuery="Two" initialFilter="unpaid" onSave={onSave} />);
  expect(screen.queryByRole('checkbox')).not.toBeInTheDocument();
  expect(screen.getByText('3 squares · 1 paid · 1 unpaid · 1 not asked yet')).toBeInTheDocument();
  expect(screen.getByText(/Applies to all of Family/)).toBeInTheDocument();
  fireEvent.click(screen.getByRole('button', { name: 'Mark remaining 2 paid for Family' }));
  await waitFor(() => expect(onSave).toHaveBeenCalledWith([1, 2], 'paid'));
  expect(screen.getByRole('status')).toHaveTextContent('Saved 2 squares as paid for Family.');
});
it('retries the exact collapsed person action without selecting rows', async () => {
  const onSave = vi.fn().mockRejectedValueOnce(new Error('Offline')).mockResolvedValue(undefined);
  render(<PaymentsPanel {...props} onSave={onSave} />);
  fireEvent.click(screen.getByRole('button', { name: 'Mark all 2 paid for Family' }));
  await screen.findByRole('alert');
  fireEvent.click(screen.getByRole('button', { name: 'Retry marking 2 paid for Family' }));
  await waitFor(() => expect(onSave).toHaveBeenCalledTimes(2));
  expect(onSave).toHaveBeenLastCalledWith([0, 1], 'paid');
});
it('invalidates a failed person action if responsibility or payment scope changes', async () => {
  const onSave = vi.fn().mockRejectedValue(new Error('Offline'));
  const { rerender } = render(<PaymentsPanel {...props} onSave={onSave} />);
  fireEvent.click(screen.getByRole('button', { name: 'Mark all 2 paid for Family' }));
  await screen.findByRole('alert');
  const changed = buildPaymentModel({ leftAxis: [], topAxis: [], squares: [['Buyer'], ['Other']], allocationLabels: ['Family', 'Someone else'] }, {});
  rerender(<PaymentsPanel {...props} model={changed} onSave={onSave} />);
  expect(screen.queryByRole('button', { name: /Retry marking/ })).not.toBeInTheDocument();
  expect(screen.getByText(/This person’s squares changed/)).toBeInTheDocument();
  expect(onSave).toHaveBeenCalledTimes(1);
});
it('keeps person actions disabled until payment persistence completes', async () => {
  let finish!: () => void;
  const onSave = vi.fn(() => new Promise<void>(resolve => { finish = resolve; }));
  render(<PaymentsPanel {...props} onSave={onSave} />);
  const button = screen.getByRole('button', { name: 'Mark all 2 paid for Family' });
  fireEvent.click(button);
  expect(button).toBeDisabled();
  expect(screen.getByRole('status')).toHaveTextContent('Saving');
  expect(screen.getByRole('status')).not.toHaveTextContent('Saved');
  fireEvent.click(button);
  expect(onSave).toHaveBeenCalledTimes(1);
  finish();
  await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('Saved 2 squares as paid for Family.'));
});
